module.exports = {
  table: 'pouring_settings',
  fields: [
    'target_ml', 'tolerance_ml', 'max_ml', 'pour_speed', 'viscosity',
    'water_color', 'show_timer', 'time_limit_seconds', 'allow_retries', 'max_retries',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_correct_id', 'sound_wrong_id', 'sound_pour_id',
    'intro_text', 'outro_text',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    target_ml: 50,
    tolerance_ml: 5,
    max_ml: 200,
    pour_speed: 1,
    viscosity: 1,
    water_color: '#4da6ff',
    show_timer: 1,
    time_limit_seconds: 0,
    allow_retries: 1,
    max_retries: 3,
    bg_color: '#f0f4ff',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
