module.exports = {
  table: 'tictactoe_settings',
  fields: [
    'board_size', 'difficulty', 'enable_board_selection', 'enable_level_selection',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'board_cell_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'o_image_url',
    'sound_correct_id', 'sound_wrong_id', 'win_sound_id', 'lose_sound_id',
    'custom_win_msg', 'try_again_btn_text', 'try_again_text_color', 'try_again_bg_color',
    'continue_btn_text', 'continue_btn_text_color', 'continue_btn_bg_color',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'thankyou_heading_text', 'thankyou_heading_color',
    'thankyou_subtitle_text', 'thankyou_subtitle_color',
    'submit_btn_text', 'submit_btn_text_color', 'submit_btn_bg_color',
    'redirect_url', 'continue_now_btn_text', 'continue_now_btn_text_color', 'continue_now_btn_bg_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url', 'o_image_url'],
  defaults: {
    board_size: '3', difficulty: 'easy',
    enable_board_selection: 1, enable_level_selection: 1,
    bg_color: '#1e293b', primary_color: '#6366f1',
    board_cell_color: '#ffffff', font_family: 'DM Sans',
    heading_1_color: '#1a1a2e', heading_2_color: '#666666',
    heading_3_color: '#777777', description_color: '#888888',
    start_button_text: 'Start Game',
  },
};
