module.exports = {
  table: 'crossword_settings',
  fields: [
    'grid_rows', 'grid_cols', 'cell_size', 'show_timer', 'time_limit_seconds',
    'allow_hints', 'auto_size',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url',
    'submit_confirm_gif_url', 'blank_cell_image_url',
    'sound_correct_id', 'sound_wrong_id',
    'intro_text', 'outro_text',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url', 'blank_cell_image_url'],
  defaults: {
    grid_rows: 10,
    grid_cols: 10,
    cell_size: 40,
    show_timer: 1,
    time_limit_seconds: 0,
    allow_hints: 1,
    auto_size: 0,
    bg_color: '#f8f8ff',
    primary_color: '#7c6ff7',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
