module.exports = {
  table: 'screw_settings',
  fields: [
    'board_rows', 'board_cols', 'block_colors', 'screws_per_block', 'empty_holes',
    'difficulty', 'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'reveal_image_url',
    'submit_confirm_gif_url',
    'sound_screw_id', 'sound_fall_id', 'sound_reveal_id',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'reveal_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'reveal_image_url', 'submit_confirm_gif_url'],
  defaults: {
    board_rows: 6,
    board_cols: 6,
    block_colors: '#c0392b,#2980b9,#27ae60,#f39c12,#8e44ad',
    screws_per_block: 2,
    empty_holes: 3,
    difficulty: 'medium',
    show_timer: 1,
    time_limit_seconds: 120,
    bg_color: '#f0e6d3',
    primary_color: '#8B4513',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
