module.exports = {
  table: 'soundify_settings',
  fields: [
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'custom_win_msg', 'custom_lose_msg',
    'try_again_btn_text', 'try_again_text_color', 'try_again_bg_color',
    'continue_btn_text', 'continue_btn_text_color', 'continue_btn_bg_color',
    'bg_color', 'primary_color', 'font_family', 'meta_description',
    'sound_correct_id', 'sound_wrong_id', 'win_sound_id', 'lose_sound_id',
    'terms_enabled', 'terms_text', 'terms_url',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'thankyou_heading_text', 'thankyou_heading_color',
    'thankyou_subtitle_text', 'thankyou_subtitle_color',
    'submit_btn_text', 'submit_btn_text_color', 'submit_btn_bg_color',
    'redirect_url', 'continue_now_btn_text', 'continue_now_btn_text_color', 'continue_now_btn_bg_color',
    'time_per_question', 'max_sound_replays',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    bg_color: '#1a1a2e',
    primary_color: '#8b5cf6',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#1a1a2e',
    heading_3_color: '#444444',
    description_color: '#666666',
    time_per_question: 30,
    max_sound_replays: 1,
  },
};
