module.exports = {
  table: 'game2048_settings',
  fields: [
    'grid_size', 'target_number', 'tile_colors',
    'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_slide_id', 'sound_merge_id', 'sound_win_id', 'sound_lose_id',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'submit_button_text', 'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text', 'continue_button_text_color', 'continue_button_bg_color',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
    'overlay_animation_in', 'claim_prize_button_text', 'new_game_button_text',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    grid_size: 4,
    target_number: 2048,
    show_timer: 0,
    time_limit_seconds: 0,
    bg_color: '#faf8ef',
    primary_color: '#8f7a66',
    font_family: 'DM Sans',
    heading_1_color: '#776e65',
    heading_2_color: '#776e65',
    heading_3_color: '#776e65',
    description_color: '#776e65',
    overlay_animation_in: 'fade',
  },
};
