module.exports = {
  table: 'stressbuster_settings',
  fields: [
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'custom_win_msg', 'try_again_btn_text', 'try_again_text_color', 'try_again_bg_color',
    'continue_btn_text', 'continue_btn_text_color', 'continue_btn_bg_color',
    'bg_color', 'primary_color', 'board_cell_color', 'font_family', 'meta_description',
    'sound_correct_id', 'sound_wrong_id', 'win_sound_id', 'lose_sound_id',
    'game_mode', 'difficulty', 'target_count', 'time_limit',
    'terms_enabled', 'terms_text', 'terms_url',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'thankyou_heading_text', 'thankyou_heading_color', 'thankyou_subtitle_text', 'thankyou_subtitle_color',
    'submit_btn_text', 'submit_btn_text_color', 'submit_btn_bg_color',
    'redirect_url', 'continue_now_btn_text', 'continue_now_btn_text_color', 'continue_now_btn_bg_color',
    'click_limit', 'timer_enabled', 'show_click_count', 'click_mode',
    'frustration_enabled', 'show_click_speed', 'show_frustration_result',
    'cat_health', 'millisecond_display', 'frustration_mode',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url', 'o_image_url',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url', 'o_image_url'],
  defaults: {
    bg_color: '#f4f6fb',
    primary_color: '#9333ea',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#1a1a2e',
    heading_3_color: '#444444',
    description_color: '#666666',
    target_count: 20,
    time_limit: 0,
    click_limit: 21,
    cat_health: 20,
  },
};
