module.exports = {
  table: 'typer_settings',
  fields: [
    'fall_speed', 'max_simultaneous', 'difficulty_mode', 'time_limit_seconds',
    'max_misses', 'target_words', 'word_category',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_correct_id', 'sound_wrong_id', 'sound_combo_id', 'sound_gameover_id',
    'show_timer', 'intro_text', 'outro_text',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    fall_speed: 2,
    max_simultaneous: 3,
    difficulty_mode: 'progressive',
    time_limit_seconds: 60,
    max_misses: 5,
    target_words: 0,
    word_category: 'mixed',
    show_timer: 1,
    bg_color: '#0f172a',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
