module.exports = {
  table: 'quiz_settings',
  fields: [
    'primary_color', 'bg_color', 'intro_text', 'outro_text', 'show_progress',
    'bg_image_url', 'thankyou_bg_image_url',
    'terms_enabled', 'terms_text', 'terms_url',
    'send_email', 'win_sound_url', 'win_sound_id', 'lose_sound_id',
    'sound_correct_id', 'sound_wrong_id', 'sound_neutral_id',
    'game_logo_url', 'font_family', 'submit_confirm_gif_url',
    'allow_back', 'time_per_question',
    'heading_1', 'heading_2', 'heading_1_color', 'heading_2_color',
    'intro_text_color', 'thankyou_subtitle', 'outro_text_color',
    'thankyou_subtitle_color', 'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'next_button_text', 'next_button_text_color', 'next_button_bg_color',
    'start_button_text', 'submit_button_text', 'continue_button_text',
    'randomize_questions', 'questions_per_session',
    'enable_mascot', 'enable_speech', 'speech_language', 'speech_rate', 'speech_pitch',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url', 'win_sound_url'],
  defaults: {
    primary_color: '#6366f1',
    bg_color: '#ffffff',
    show_progress: 1,
    send_email: 1,
    font_family: 'DM Sans',
    allow_back: 0,
    time_per_question: 0,
    heading_1_color: '#1a1a2e',
    heading_2_color: '#1a1a2e',
    intro_text_color: '#444444',
    outro_text_color: '#1a1a2e',
    thankyou_subtitle_color: '#444444',
    start_button_text_color: '#ffffff',
    submit_button_text_color: '#ffffff',
    continue_button_text_color: '#ffffff',
    next_button_text: 'Next →',
    next_button_text_color: '#ffffff',
    randomize_questions: 0,
    questions_per_session: 0,
    enable_mascot: 0,
    enable_speech: 0,
    speech_language: 'en',
    speech_rate: 1,
    speech_pitch: 1,
    terms_enabled: 0,
  },
};
