module.exports = {
  table: 'jigsaw_settings',
  fields: [
    'grid_cols', 'grid_rows', 'allow_difficulty_selection',
    'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'puzzle_image_url',
    'submit_confirm_gif_url',
    'sound_correct_id', 'sound_wrong_id',
    'intro_text', 'outro_text',
    'submit_button_text', 'submit_btn_text',
    'continue_button_text', 'continue_now_btn_text',
    'start_button_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'submit_btn_text_color', 'submit_btn_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'continue_now_btn_text_color', 'continue_now_btn_bg_color',
    'thankyou_heading_text', 'thankyou_heading_color',
    'thankyou_subtitle_text', 'thankyou_subtitle_color',
    'outro_text_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'puzzle_image_url', 'submit_confirm_gif_url'],
  defaults: {
    grid_cols: 4,
    grid_rows: 4,
    allow_difficulty_selection: 0,
    show_timer: 1,
    time_limit_seconds: 0,
    bg_color: '#f8f8ff',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
    outro_text_color: '#1a1a2e',
    thankyou_heading_color: '#1a1a2e',
    thankyou_subtitle_color: '#444444',
  },
};
