module.exports = {
  table: 'simon_settings',
  fields: [
    'num_rounds', 'num_colors', 'speed',
    'color_1', 'color_2', 'color_3', 'color_4', 'color_5', 'color_6',
    'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_correct_id', 'sound_wrong_id', 'sound_gameover_id',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    num_rounds: 8,
    num_colors: 4,
    speed: 'medium',
    color_1: '#ef4444',
    color_2: '#3b82f6',
    color_3: '#22c55e',
    color_4: '#f59e0b',
    color_5: '#8b5cf6',
    color_6: '#ec4899',
    show_timer: 0,
    time_limit_seconds: 0,
    bg_color: '#1a1a2e',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
