module.exports = {
  table: 'stack_settings',
  fields: [
    'block_width', 'block_height', 'base_speed', 'speed_increase',
    'show_timer', 'time_limit_seconds',
    'block_color', 'block_color_2',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_place_id', 'sound_slice_id', 'sound_gameover_id',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    block_width: 200,
    block_height: 30,
    base_speed: 3.0,
    speed_increase: 0.15,
    show_timer: 1,
    time_limit_seconds: 0,
    block_color: '#6366f1',
    block_color_2: '#4f46e5',
    bg_color: '#0f172a',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
