module.exports = {
  table: 'catch_settings',
  fields: [
    'spawn_rate', 'fall_speed', 'max_misses', 'time_limit_seconds',
    'item_type', 'basket_color',
    'show_timer',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_catch_id', 'sound_miss_id', 'sound_gameover_id',
    'intro_text', 'outro_text',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'intro_text_color', 'outro_text_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    spawn_rate: 1000,
    fall_speed: 2,
    max_misses: 5,
    time_limit_seconds: 60,
    item_type: 'emoji',
    basket_color: '#8B5CF6',
    show_timer: 1,
    bg_color: '#f8f8ff',
    primary_color: '#8B5CF6',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
