module.exports = {
  table: 'carlaunch_settings',
  fields: [
    'car_make', 'car_model', 'car_year', 'car_trim',
    'engine_hp', 'engine_torque', 'engine_cylinders', 'engine_displacement',
    'weight_kg', 'drivetrain', 'transmission_type', 'gears',
    'zero_to_60', 'quarter_mile', 'car_model_url',
    'color_options', 'default_color',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_start_id', 'sound_shift_id', 'sound_finish_id',
    'show_timer', 'time_limit_seconds',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    car_year: 2024,
    weight_kg: 1500,
    drivetrain: 'RWD',
    transmission_type: 'Automatic',
    gears: 8,
    default_color: '#ef4444',
    bg_color: '#0f172a',
    primary_color: '#ef4444',
    font_family: 'DM Sans',
    show_timer: 1,
    time_limit_seconds: 0,
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
