module.exports = {
  table: 'flappy_settings',
  fields: [
    'gravity', 'flap_strength', 'pipe_speed', 'pipe_gap', 'pipe_width',
    'bird_color', 'pipe_color', 'ground_color', 'sky_color',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'show_timer', 'time_limit_seconds',
    'sound_flap_id', 'sound_score_id', 'sound_gameover_id',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text', 'continue_button_text_color', 'continue_button_bg_color',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    gravity: 0.5, flap_strength: -8, pipe_speed: 3, pipe_gap: 150, pipe_width: 60,
    bird_color: '#f59e0b', pipe_color: '#22c55e',
    ground_color: '#8B4513', sky_color: '#87CEEB',
    bg_color: '#87CEEB', primary_color: '#f59e0b', font_family: 'DM Sans',
    show_timer: 1, time_limit_seconds: 0,
    heading_1_color: '#1a1a2e', heading_2_color: '#666666',
    heading_3_color: '#777777', description_color: '#888888',
  },
};
