module.exports = {
  table: 'maze_settings',
  fields: [
    'total_levels', 'grid_size_min', 'grid_size_max',
    'show_timer', 'time_limit_seconds',
    'collectible_count', 'collectible_label', 'collectible_images',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'wall_color', 'path_color',
    'sound_collect_id', 'sound_complete_id',
    'overlay_animation_in', 'overlay_animation_out',
    'intro_text', 'outro_text', 'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
  ],
  uploads: [],
  defaults: {
    total_levels: 50,
    grid_size_min: 5,
    grid_size_max: 20,
    show_timer: 1,
    time_limit_seconds: 0,
    collectible_count: 3,
    collectible_label: '★',
    bg_color: '#0f172a',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    wall_color: '#1e293b',
    path_color: '#ffffff',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
    overlay_animation_in: 'flyFromBottom',
    overlay_animation_out: 'flyToTop',
  },
};
