module.exports = {
  table: 'memory_settings',
  fields: [
    'grid_cols', 'grid_rows', 'card_shape',
    'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url',
    'card_cover_image_url', 'overlay_image_url', 'submit_confirm_gif_url',
    'sound_flip_id', 'sound_match_id', 'sound_nomatch_id', 'win_sound_id',
    'overlay_animation_in', 'overlay_animation_out', 'overlay_idle_time', 'overlay_duration',
    'intro_text', 'outro_text',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
    'redirect_url', 'redirect_delay', 'redirect_open_new_tab',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
    'next_button_text', 'next_button_text_color', 'next_button_bg_color',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'card_cover_image_url', 'overlay_image_url', 'submit_confirm_gif_url'],
  defaults: {
    grid_cols: 4,
    grid_rows: 4,
    card_shape: 'square',
    show_timer: 1,
    time_limit_seconds: 0,
    bg_color: '#f8f8ff',
    primary_color: '#6366f1',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
    overlay_animation_in: 'flyFromBottom',
    overlay_animation_out: 'flyToTop',
    overlay_idle_time: 3,
    overlay_duration: 3,
  },
};
