module.exports = {
  table: 'connect4_settings',
  fields: [
    'board_rows', 'board_cols', 'win_count', 'player_color', 'ai_color', 'board_color',
    'difficulty', 'show_timer', 'time_limit_seconds',
    'heading_1', 'heading_2', 'heading_3', 'description_text',
    'heading_1_color', 'heading_2_color', 'heading_3_color', 'description_color',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url',
    'sound_drop_id', 'sound_win_id', 'sound_draw_id',
    'intro_text', 'intro_text_color', 'outro_text', 'outro_text_color',
    'submit_button_text', 'continue_button_text', 'start_button_text',
    'terms_enabled', 'terms_text', 'terms_url', 'meta_description',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'start_button_text_color', 'start_button_bg_color',
    'submit_button_text_color', 'submit_button_bg_color',
    'continue_button_text_color', 'continue_button_bg_color',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'submit_confirm_gif_url'],
  defaults: {
    board_rows: 6,
    board_cols: 7,
    win_count: 4,
    player_color: '#ef4444',
    ai_color: '#fbbf24',
    board_color: '#3b82f6',
    difficulty: 'medium',
    show_timer: 1,
    time_limit_seconds: 0,
    bg_color: '#0f172a',
    primary_color: '#3b82f6',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#666666',
    heading_3_color: '#777777',
    description_color: '#888888',
  },
};
