module.exports = {
  table: 'spin_settings',
  fields: [
    'heading_1', 'heading_1_color', 'heading_2', 'heading_2_color',
    'description_text', 'description_color',
    'spin_mode', 'win_message', 'lose_message',
    'wheel_bg_color', 'pointer_color', 'center_color', 'center_label',
    'bg_color', 'primary_color', 'font_family',
    'bg_image_url', 'thankyou_bg_image_url', 'game_logo_url',
    'center_image_url', 'submit_confirm_gif_url',
    'sound_spin_id', 'sound_win_id', 'sound_lose_id',
    'redirect_url', 'redirect_delay', 'redirect_open_new_tab',
    'continue_button_text', 'continue_button_text_color', 'continue_button_bg_color',
    'meta_description', 'outro_text', 'outro_text_color',
    'thankyou_subtitle', 'thankyou_subtitle_color',
    'submit_button_text', 'submit_button_text_color', 'submit_button_bg_color',
    'start_button_text', 'start_button_text_color', 'start_button_bg_color',
    'terms_enabled', 'terms_text', 'terms_url',
  ],
  uploads: ['bg_image_url', 'thankyou_bg_image_url', 'game_logo_url', 'center_image_url', 'submit_confirm_gif_url'],
  defaults: {
    spin_mode: 'once',
    wheel_bg_color: '#FFFFFF',
    pointer_color: '#EF4444',
    center_color: '#1F2937',
    center_label: 'SPIN',
    bg_color: '#F8F8FF',
    primary_color: '#7C6FF7',
    font_family: 'DM Sans',
    heading_1_color: '#1a1a2e',
    heading_2_color: '#1a1a2e',
    description_color: '#666666',
    redirect_delay: 3,
    redirect_open_new_tab: 0,
    continue_button_text: 'Continue →',
    continue_button_text_color: '#ffffff',
    terms_enabled: 0,
  },
};
