name: Auto Deploy
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update backend on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/quiz-platform/pro
            git fetch origin
            git reset --hard origin/main
            npm install --legacy-peer-deps --no-audit --no-fund
            pm2 restart quiz-backend --update-env
            echo "Backend deployed"
